name: BuildTest

# Every push, we do build and testing process.
on: push

jobs:
  BuildTest:
    # Name the Job
    name: Build the code, Test code using Gradlew

    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Server
        run: |
          wget https://github.com/Navi-Cloud/Navi-Server/releases/download/v0.4.0-ALPHA/NavIServer-1.0-SNAPSHOT.jar -O /tmp/testServer.jar
          mkdir -p /tmp/kdrTesting
          cat << EOF > /tmp/application-test.properties
          spring.jpa.show-sql=true
          spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
          spring.h2.console.enabled=true
          navi.server-root=/tmp/kdrTesting
          EOF
          java -jar /tmp/testServer.jar --spring.config.location=/tmp/application-test.properties &

      - name: Build Application/Test
        run: ./gradlew --no-daemon --info build